services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks:
      - webui-network
      - host
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - webui-network
    depends_on:
      - webui

networks:
  webui-network:
    driver: bridge
  host:
    external: true

volumes:
  open-webui:
  caddy_data:
  caddy_config:
