services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    volumes:
      - ./data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - webui

volumes:
  open-webui:
  caddy_data:
  caddy_config:
