services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/backend/data
    environment:
      DOMAIN: ${DOMAIN:-http://localhost:8080}
    restart: unless-stopped

volumes:
  open-webui:
